version: '3.9'

services:

  db:
    container_name: postgres
    image: postgres:latest
    restart: always
    # set shared memory limit when using docker-compose
    shm_size: 128mb
    volumes:
      - ./docker-postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: project
      POSTGRES_PASSWORD: secret
      POSTGRES_USER: root
